name: Weekly n8n Workflow Backup

on:
  schedule:
    - cron: "0 0 * * 0" 
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Backup Date
        run: echo "BACKUP_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Fetch Workflows from n8n
        run: |
          mkdir -p tmp_workflows
          curl -X 'GET' "https://n8n.atozserver.cfd/api/v1/workflows" \
          -H "accept: application/json" \
          -H "X-N8N-API-KEY: ${{ secrets.N8N_API_KEY }}" \
          -o tmp_workflows/workflows.json

      - name: Split Workflows into Separate Files
        run: |
          BACKUP_DATE=${{ env.BACKUP_DATE }}
          mkdir -p backups/$BACKUP_DATE
          jq -c '.data[]' tmp_workflows/workflows.json | while read -r workflow; do
            ID=$(echo $workflow | jq -r '.id')
            NAME=$(echo $workflow | jq -r '.name' | tr ' ' '_' | tr -d '[:punct:]')  # Safe filename
            FILENAME="workflow_${NAME}_${ID}.json"
            echo $workflow | jq '.' > backups/$BACKUP_DATE/$FILENAME
          done
          rm -rf tmp_workflows

      - name: Commit and Push Changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "n8n Backup Bot"
          git add backups/*
          git commit -m "Weekly n8n workflow backup - ${{ env.BACKUP_DATE }}" || exit 0
          git push origin main
